### ISSUE TITLE
working well with demo video but prompting error when giving my .mp4 video file as an input

### ISSUE THREAD

**Issue by HimanshuN** [sannies/rtp2dash#1]
Hello, 
This work well with your demo video but when I am trying to give my .mp4 video as an input, it is giving me this error
Stream map '0:2' matches no streams.
To ignore this, add a trailing '?' to the map.

Can you please help me with this as I am very new in this streaming field.
Thank you

**Comment by sannies** [comment]
Hi HimanshunN,
this is a question for an ffmpeg forum. I'm happy to answer simple questions for the java part but I cannot invest too much time as no one pays me for answering questions.
Best Regards,
Sebastian
